import Head from "next/head";

export default function CustomHead({title} : {title:string}) {
    return <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/logo.svg"/>
        <link
            href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@600&family=Fredoka+One&display=swap"
            rel="stylesheet" />
    </Head>
}