import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
    return (
        <Html>
            <Head >
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/logo.svg"/>
                <link
                    href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@600&family=Fredoka+One&display=swap"
                    rel="stylesheet" />
            </Head>
        <body>
            <Main />
        <NextScript />
        </body>
        </Html>
    )
}