import Head from 'next/head'
import MainDescription from "../components/MainDescription";
import MainCoreFeatures from "../components/MainCoreFeatures/MainCoreFeatures";

export default function Home() {
    return (
        <div className="h-screen flex flex-col items-center">
            <Head>
                <title>Ahorrar Más App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/logo.svg"/>
            </Head>
            <main className="container p-4 flex flex-col items-center scroll-smooth">
                <MainDescription />
                <MainCoreFeatures />
            </main>
        </div>
    )
}
